/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peliculas.Clientes;

import com.mycompany.peliculas.PanelMain;
import com.mycompany.peliculas.Peliculas.PanelPeliculas;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lei
 */
public class PanelClientes extends javax.swing.JFrame {

    /**
     * Creates new form PanelClientes
     */
    //"modificar" es usada para que el boton guardar sepa si tiene que crear una nueva entrada o modificar una existente
    private boolean modificar = false;
    //lista para manejar los datos
    List<Cliente> lista = new ArrayList();
    
    public PanelClientes() {
        initComponents();
        llenarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tglId = new javax.swing.JToggleButton();
        tglNombre = new javax.swing.JToggleButton();
        tglDNI = new javax.swing.JToggleButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JToggleButton();
        Peliculas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tglId.setText("ID");
        tglId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglIdActionPerformed(evt);
            }
        });

        tglNombre.setText("Nombre");
        tglNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglNombreActionPerformed(evt);
            }
        });

        tglDNI.setText("DNI");
        tglDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglDNIActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("DNI:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        Peliculas.setText("Peliculas");

        listClientes.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        listClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                listClientesFocusGained(evt);
            }
        });
        listClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listClientesMouseClicked(evt);
            }
        });
        listClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listClientes);

        jLabel1.setText("ID:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido:");

        btnMostrar.setText("Info");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Direccion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tglId)
                                .addGap(18, 18, 18)
                                .addComponent(tglNombre)
                                .addGap(44, 44, 44)
                                .addComponent(tglDNI)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnMostrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGuardar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtDNI)))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglId)
                    .addComponent(tglNombre)
                    .addComponent(tglDNI)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrar)
                            .addComponent(btnEliminar)
                            .addComponent(btnBuscar))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     

    private String clientToString(Cliente cliente){
        return cliente.getIdCliente() + ";" + cliente.getNombreApellido() + ";" + cliente.getDireccion()
                 + ";" + cliente.getDni();
    }
    
    private Cliente StringToClient(String string){
       String[] partes = string.split(";");
       Cliente cliente = new Cliente(Integer.parseInt(partes[0]), partes[1], partes[2], Integer.parseInt(partes[3]));
       return cliente;
    }
        private void llenarClientes(){
            /*
        Cliente cliente = new Cliente(1563, "Martin Gomez","San Martin 4219", 42150225);
        Cliente cliente2 = new Cliente(1539, "Fernanda Ludueña", "Moncalvo 8624", 25368741);
        Cliente cliente3 = new Cliente(1534, "Lucas Platner", "Antartida Argentina 2563", 42705369);
        Cliente cliente4 = new Cliente(1587, "Luna Clara", "Rafael Carrillo 1389", 42150125);
        
        lista.add(cliente);
        lista.add(cliente2);
        lista.add(cliente3);
        lista.add(cliente4);
            */
      
       try {
            String buffer;
            BufferedReader reader = new BufferedReader(new FileReader("clientes.txt"));
            while((buffer = reader.readLine()) != null){
                lista.add(StringToClient(buffer));
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        actualizar();
    }
    private void tglIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglIdActionPerformed
        int i = 0;
        boolean cambio = true;
        Cliente cliente = new Cliente();
        while(i < lista.size()-1 && cambio) {
            cambio = false;
            for (int j = 0; j < lista.size()-1-i; j++) {
                if(lista.get(j).getIdCliente() > lista.get(j+1).getIdCliente()){
                    cliente = lista.get(j);
                    lista.set(j, lista.get(j+1));
                    lista.set(j+1, cliente);
                    cambio = true;
                }

            }
            i++;
        }
        actualizar();
    }//GEN-LAST:event_tglIdActionPerformed

    private void tglNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglNombreActionPerformed
        int i = 0;
        boolean cambio = true;
        Cliente cliente = new Cliente();
        while(i < lista.size()-1 && cambio) {
            cambio = false;
            for (int j = 0; j < lista.size()-1-i; j++) {
                if(lista.get(j).getNombreApellido().compareTo(lista.get(j+1).getNombreApellido()) > 0){
                    cliente = lista.get(j);
                    lista.set(j, lista.get(j+1));
                    lista.set(j+1, cliente);
                    cambio = true;
                }
            }
            i++;
        }
        actualizar();
    }//GEN-LAST:event_tglNombreActionPerformed

    private void tglDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglDNIActionPerformed
        int i = 0;
        boolean cambio = true;
        Cliente cliente = new Cliente();
        while(i < lista.size()-1 && cambio) {
            cambio = false;
            for (int j = 0; j < lista.size()-1-i; j++) {
                if(lista.get(j).getDni() > lista.get(j+1).getDni()){
                    cliente = lista.get(j);
                    lista.set(j, lista.get(j+1));
                    lista.set(j+1, cliente);
                    cambio = true;
                }
            }
            i++;
        }
        actualizar();
    }//GEN-LAST:event_tglDNIActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTexto();
        modificar = false;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int dni = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "DNI: "));
        int i = 0;
        boolean found = false;
        while(i < lista.size() && !found){
            if(dni == lista.get(i).getDni()){
                found = true;
            }else{
                i++;
            }
        }
        if(found){
            listClientes.setSelectedIndex(i);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cliente no registrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int i = listClientes.getSelectedIndex();
        Cliente cliente = new Cliente();
        cliente.setNombreApellido(this.txtNombre.getText() + " "  + this.txtApellido.getText());
        cliente.setIdCliente(Integer.parseInt(this.txtID.getText()));
        cliente.setDireccion(this.txtDireccion.getText());
        cliente.setDni(Integer.parseInt(this.txtDNI.getText()));

        if(modificar){
            lista.set(i, cliente);
            modificar = false;
        }else{
            lista.add(cliente);
        }
        actualizar();
        limpiarTexto();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void listClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listClientesFocusGained
        int i = this.listClientes.getSelectedIndex();
        Cliente cliente = lista.get(i);
        String[] nombre = cliente.getNombreApellido().split(" ");
        
        this.txtApellido.setText(nombre[1]);
        this.txtDNI.setText(Integer.toString(cliente.getDni()));
        this.txtDireccion.setText(cliente.getDireccion());   
        this.txtNombre.setText(nombre[0]);
        this.txtID.setText(Integer.toString(cliente.getIdCliente()));
        
        modificar = true;
    }//GEN-LAST:event_listClientesFocusGained

    private void listClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listClientesMouseClicked
         int i = this.listClientes.getSelectedIndex();
        Cliente cliente = lista.get(i);
        String[] nombre = cliente.getNombreApellido().split(" ");
        
        this.txtApellido.setText(nombre[1]);
        this.txtDNI.setText(Integer.toString(cliente.getDni()));
        this.txtDireccion.setText(cliente.getDireccion());   
        this.txtNombre.setText(nombre[0]);
        this.txtID.setText(Integer.toString(cliente.getIdCliente()));
        modificar = true;
    }//GEN-LAST:event_listClientesMouseClicked

    private void listClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listClientesValueChanged
           int i = this.listClientes.getSelectedIndex();
        Cliente cliente = lista.get(i);
        String[] nombre = cliente.getNombreApellido().split(" ");
        
        this.txtApellido.setText(nombre[1]);
        this.txtDNI.setText(Integer.toString(cliente.getDni()));
        this.txtDireccion.setText(cliente.getDireccion());   
        this.txtNombre.setText(nombre[0]);
        this.txtID.setText(Integer.toString(cliente.getIdCliente()));
        modificar = true;
    }//GEN-LAST:event_listClientesValueChanged

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        int i = listClientes.getSelectedIndex();
        if(i == -1){
            JOptionPane.showMessageDialog(rootPane, "Seleccione un cliente");
        }else{
            Cliente cliente = lista.get(i);
            JOptionPane.showMessageDialog(rootPane, "Nombre : " + cliente.getNombreApellido() +
                "\nDNI : " + cliente.getDni() +
                "\nDireccion : " + cliente.getDireccion() +
                "\nID : " + cliente.getIdCliente() +
                "\nUltimo alquiler : " + cliente.getMasReciente().getNombre());
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int i = listClientes.getSelectedIndex();
        lista.remove(i);
        actualizar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        actualizarTxt();
        PanelMain volver = new PanelMain();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    
        private void actualizar(){
        DefaultListModel dato = new DefaultListModel();
        Cliente cliente = new Cliente();
        for (int i = 0; i < lista.size(); i++) {  
            cliente = lista.get(i);
            dato.addElement(cliente.toString());
        }
        this.listClientes.setModel(dato);
        listClientes.clearSelection();
    }
    
    private void limpiarTexto(){
        this.txtApellido.setText(null);
        this.txtNombre.setText(null);
        this.txtDNI.setText(null);
        this.txtDireccion.setText(null);
        this.txtID.setText(null);
        
    }
    

    private void actualizarTxt(){       
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("clientes.txt"));
            for (int i = 0; i < lista.size(); i++) {  
                writer.write(clientToString(lista.get(i))+ "\n");
            }
                writer.close();
            
        } catch (IOException ex) {
            Logger.getLogger(PanelPeliculas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Peliculas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listClientes;
    private javax.swing.JToggleButton tglDNI;
    private javax.swing.JToggleButton tglId;
    private javax.swing.JToggleButton tglNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
